#*===================================
#* For analysis of your full Code   ||
#*============================================================
#* Invoked from the command line by running `flutter analyze`||
#*=============================================================

include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 120
  trailing_commas: preserve

linter:
  rules:
    avoid_print: true
    require_trailing_commas: true
    prefer_single_quotes: true
    constant_identifier_names: false
    non_constant_identifier_names: false
